name: Windows RDP 6 Hours Free

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 360
    steps:
    - name: Setup RDP
      run: |
        echo "Downloading RDP setup..."
        powershell -Command "Set-ExecutionPolicy Bypass -Scope Process -Force; Invoke-WebRequest https://raw.githubusercontent.com/rdp-wrap/setup/main/setup.ps1 -OutFile setup.ps1; ./setup.ps1"
    - name: Keep Alive
      run: |
        echo "RDP is running for 6 hours..."
        Start-Sleep -Seconds 21600
